config/routes.rb
Bolao::Application.routes.draw do
  resources :championships

  get "home/index"

  resources :groups

  resources :matches

  resources :teams

  resources :gambles

  devise_for :users
  
  match  'update_or_create_all_gambles' => 'gambles#update_or_create_all_gambles'

  root :to => 'home#index'

end

app/models/gamble.rb
class Gamble < ActiveRecord::Base
  belongs_to :user
  belongs_to :match
  attr_accessible :integer, :team_away_score, :team_home_score, :match_id
end

app/controllers/gambles_controller.rb
class GamblesController < ApplicationController
  # GET /gambles
  # GET /gambles.json
  def index
    @gambles = Gamble.all
    @groups = Group.actives
    @user_gambles = Gamble.find_all_by_user_id(current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gambles }
    end
  end

  # GET /gambles/1
  # GET /gambles/1.json
  def show
    @gamble = Gamble.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gamble }
    end
  end

  # GET /gambles/new
  # GET /gambles/new.json
  def new
    @gamble = Gamble.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gamble }
    end
  end

  # GET /gambles/1/edit
  def edit
    @gamble = Gamble.find(params[:id])
  end

  # POST /gambles
  # POST /gambles.json
  def create
    @gamble = Gamble.new(params[:gamble])

    respond_to do |format|
      if @gamble.save
        format.html { redirect_to @gamble, notice: 'Gamble was successfully created.' }
        format.json { render json: @gamble, status: :created, location: @gamble }
      else
        format.html { render action: "new" }
        format.json { render json: @gamble.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gambles/1
  # PUT /gambles/1.json
  def update
    @gamble = Gamble.find(params[:id])

    respond_to do |format|
      if @gamble.update_attributes(params[:gamble])
        format.html { redirect_to @gamble, notice: 'Gamble was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gamble.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gambles/1
  # DELETE /gambles/1.json
  def destroy
    @gamble = Gamble.find(params[:id])
    @gamble.destroy

    respond_to do |format|
      format.html { redirect_to gambles_url }
      format.json { head :no_content }
    end
  end
  
  def update_or_create_all_gambles
    respond_to do |format|
      gambles = params[:matchgamble]
      id_match = 0
      i = 0
      gambles.each do |gamble|
        gamble.each do |ga|
          if ga["all_gambles"].present?
            gahash = ga["all_gambles"].to_hash
            @gamble = Gamble.find_by_user_id_and_match_id(current_user.id,gamble[0])
            id_match = gamble[0]
            @gamble = Gamble.new() if !@gamble.present? 
            @gamble.team_home_score = gahash["team_home_score"].to_i
            @gamble.team_away_score = gahash["team_away_score"].to_i
            @gamble.user = current_user if !@gamble.user.present?
            @gamble.match_id = gamble[0].to_i if !@gamble.match_id.present?
            @gamble.save if (gahash["team_home_score"].present? && gahash["team_away_score"].present? )          
           # puts "User = #{current_user.id}  Id = #{gamble[0]} gol1 =  #{gahash["team_home_score"].to_s} gol 2 = #{gahash["team_away_score"].to_s}"
          end
        end
      end
      @gambles = Gamble.all
      @groups = Group.actives
      @user_gambles = Gamble.find_all_by_user_id(current_user.id)
      flash[:notice] =  "Apostas salvas com sucesso!"
      flash[:id_match] = id_match.to_s 
      format.js
    end
    #respond_to do |format|
     # format.html{render action: "edit"}
    #end 
  end
end

app/helpers/gambles_helper.rb
module GamblesHelper
end

app/views/gambles/_form.html.erb
<%= form_for(@gamble) do |f| %>
  <% if @gamble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gamble.errors.count, "error") %> prohibited this gamble from being saved:</h2>

      <ul>
      <% @gamble.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_home_score %><br />
    <%= f.text_field :team_home_score %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :team_away_score %><br />
    <%= f.number_field :team_away_score %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gambles/_gambles.html.erb
<h3><%= @groups.first.championship.name if @groups.present? and @groups.first.championship.present? %></h3>
<% if @groups.present?%>
	  <% @groups.each do |g| %>
		
		  <div class="container">
				  <div class="span12" style="margin:-10px 0 0 250px"><strong>Grupo <%=g.name%></strong></div>
				  <% @show_flash = false %>
				  <%= form_for :gamble,:remote=>true,  :url => update_or_create_all_gambles_path do |x| %>
			          <% g.matches.each do |m| %>
						<% @ug = @user_gambles.select{|ug| ug.match_id == m.id }%>
						<% @show_flash = (m.id.to_s == flash[:id_match]) %>
						<%= fields_for "matchgamble[#{m.id.to_s}][all_gambles]",  Gamble.new() do |g|  %>
						  		<div class="row" style="background-color:white">
							        <div class="span2" style="text-align: right"><%= standart_date(m.date_match, "/") %></div>
									<div class="span1" style="text-align: left"><%= m.team_home.name%></div>
									<% @team_home_score = "" %>
									<% @team_away_score = "" %>
									<% if @ug.present? %>
										<% @team_home_score = @ug[0].team_home_score%>
										<% @team_away_score = @ug[0].team_away_score%>
									<% end %>
									<div class="span" style="text-align: left"><%= g.text_field :team_home_score, :value => @team_home_score, :style=>"width:15px;" %></div>
								    <div class="span" style="text-align: left"><%= %></div>
								    <div class="span" style="text-align: left">X</div>
								    <div class="span1" style="text-align: left"><%= g.text_field :team_away_score, :value => @team_away_score,  :style=>"width:15px;" %></div>
								    <div class="span2" style="text-align: left"><%= m.team_alway.name%></div>
								</div>							
							<% end %>
	  		          <% end %>	
     			 <%= submit_tag :Salvar, :class => 'btn btn-small btn-primary' %>
		        <% if @show_flash and flash[:notice]  %>				
			        <div class="alert">
			           <button type="button" class="close" data-dismiss="alert">×</button>
			           <strong><%= flash[:notice] %></strong><br/>
			        </div>
		  		<% end %>
		        <% end %>
				
		  </div>
						<div style="text-align:center">	---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- </div>
	  <% end %>		  
	<% end %>

app/views/gambles/edit.html.erb
<h1>Editing gamble</h1>

<%= render 'form' %>

<%= link_to 'Show', @gamble %> |
<%= link_to 'Back', gambles_path %>

app/views/gambles/index.html.erb
<div id="gambles_div">
  <%= render "gambles"%>
</div>
<div>
	<%= link_to 'Logout', destroy_user_session_path, :method=> :delete, :confirm => 'Deseja efetuar logoff?'%>
</div>

app/views/gambles/new.html.erb
<h1>New gamble</h1>

<%= render 'form' %>

<%= link_to 'Back', gambles_path %>

app/views/gambles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Team home score:</b>
  <%= @gamble.team_home_score %>
</p>

<p>
  <b>Integer:</b>
  <%= @gamble.integer %>
</p>

<p>
  <b>Team away score:</b>
  <%= @gamble.team_away_score %>
</p>

<p>
  <b>User:</b>
  <%= @gamble.user %>
</p>


<%= link_to 'Edit', edit_gamble_path(@gamble) %> |
<%= link_to 'Back', gambles_path %>

app/views/gambles/update_or_create_all_gambles.js.erb
$("#gambles_div").html("<%= escape_javascript(render(:partial => 'gambles')) %>");
//$('#bottom-div').find('a').trigger('click');