config/routes.rb
Bolao::Application.routes.draw do
  resources :championships

  get "home/index"

  resources :groups

  resources :matches

  resources :teams

  resources :gambles

  devise_for :users
  
  match  'update_or_create_all_gambles' => 'gambles#update_or_create_all_gambles'

  root :to => 'home#index'

end

app/models/championship.rb
class Championship < ActiveRecord::Base
  attr_accessible :active, :desc, :end_date, :name, :start_date
  has_and_belongs_to_many :users
  has_many :groups
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  # GET /championships
  # GET /championships.json
  def index
    @championships = Championship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @championships }
    end
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
    @championship = Championship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @championship }
    end
  end

  # GET /championships/new
  # GET /championships/new.json
  def new
    @championship = Championship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @championship }
    end
  end

  # GET /championships/1/edit
  def edit
    @championship = Championship.find(params[:id])
  end

  # POST /championships
  # POST /championships.json
  def create
    @championship = Championship.new(params[:championship])

    respond_to do |format|
      if @championship.save
        format.html { redirect_to @championship, notice: 'Championship was successfully created.' }
        format.json { render json: @championship, status: :created, location: @championship }
      else
        format.html { render action: "new" }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /championships/1
  # PUT /championships/1.json
  def update
    @championship = Championship.find(params[:id])

    respond_to do |format|
      if @championship.update_attributes(params[:championship])
        format.html { redirect_to @championship, notice: 'Championship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship = Championship.find(params[:id])
    @championship.destroy

    respond_to do |format|
      format.html { redirect_to championships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_form.html.erb
<%= form_for(@championship) do |f| %>
  <% if @championship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@championship.errors.count, "error") %> prohibited this championship from being saved:</h2>

      <ul>
      <% @championship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/championships/edit.html.erb
<h1>Editing championship</h1>

<%= render 'form' %>

<%= link_to 'Show', @championship %> |
<%= link_to 'Back', championships_path %>

app/views/championships/index.html.erb
<h1>Listing championships</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Desc</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @championships.each do |championship| %>
  <tr>
    <td><%= championship.name %></td>
    <td><%= championship.desc %></td>
    <td><%= championship.start_date %></td>
    <td><%= championship.end_date %></td>
    <td><%= championship.active %></td>
    <td><%= link_to 'Show', championship %></td>
    <td><%= link_to 'Edit', edit_championship_path(championship) %></td>
    <td><%= link_to 'Destroy', championship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Championship', new_championship_path %>

app/views/championships/new.html.erb
<h1>New championship</h1>

<%= render 'form' %>

<%= link_to 'Back', championships_path %>

app/views/championships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @championship.name %>
</p>

<p>
  <b>Desc:</b>
  <%= @championship.desc %>
</p>

<p>
  <b>Start date:</b>
  <%= @championship.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @championship.end_date %>
</p>

<p>
  <b>Active:</b>
  <%= @championship.active %>
</p>


<%= link_to 'Edit', edit_championship_path(@championship) %> |
<%= link_to 'Back', championships_path %>