config/routes.rb
Bolao::Application.routes.draw do
  resources :championships

  get "home/index"

  resources :groups

  resources :matches

  resources :teams

  resources :gambles

  devise_for :users
  
  match  'update_or_create_all_gambles' => 'gambles#update_or_create_all_gambles'

  root :to => 'home#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :team_home, :class_name => 'Team', :foreign_key => 'team_home_id'
  belongs_to :team_alway, :class_name => 'Team', :foreign_key => 'team_alway_id'
  belongs_to :group
  has_many :matches
  attr_accessible :date_match, :score_team_away, :score_team_home, :team_home_id, :team_alway_id, :group_id
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_filter :load_basics, :only => [:edit, :new]
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
    
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render json: @match, status: :created, location: @match }
      else
        format.html { render action: "new" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end
  
private

    def load_basics
      @teams = Team.all
      @groups = Group.all
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :grupo %><br />
    <%= f.select :group_id, @groups.map {|g| [g.name,g.id] } %>
  </div>
  <div class="field">
    <%= f.label :time_da_casa %><br />
    <%= f.select :team_home_id, @teams.map {|t| [t.name,t.id] } %>
  </div>
  <div class="field">
    <%= f.label :time_visitante %><br />
    <%= f.select :team_alway_id, @teams.map {|t| [t.name,t.id] } %>
  </div>
  <div class="field">
    <%= f.label :score_team_home %><br />
    <%= f.number_field :score_team_home %>
  </div>
  <div class="field">
    <%= f.label :score_team_away %><br />
    <%= f.number_field :score_team_away %>
  </div>
  <div class="field">
    <%= f.label :date_match %><br />
    <%= f.datetime_select :date_match %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>Time da casa</th>
    <th>Time Visitante</th>
    <th>Score team home</th>
    <th>Score team away</th>
    <th>Date match</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.team_home.name if match.team_home.present? %></td>
    <td><%= match.team_alway.name if match.team_alway.present? %></td>
    <td><%= match.score_team_home %></td>
    <td><%= match.score_team_away %></td>
    <td><%= match.date_match %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time da casa:</b>
  <%= @match.team_home.name %>
</p>

<p>
  <b>Id team alway:</b>
  <%= @match.team_alway.name %>
</p>

<p>
  <b>Time visitante:</b>
  <%= @match.score_team_home %>
</p>

<p>
  <b>Score team away:</b>
  <%= @match.score_team_away %>
</p>

<p>
  <b>Date match:</b>
  <%= @match.date_match %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>